kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.componentId }}-kafka-ui
  namespace: {{ .Values.applicationId }}-{{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.componentId }}-kafka-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.componentId }}-kafka-ui
    spec:
      containers:
        - name: {{ .Values.componentId }}-kafka-ui
          image: 'provectuslabs/kafka-ui:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: '{{ .Values.componentId }}-kafka-bootstrap:9092'
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600