apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{.Values.name}}-quarkus-pipeline
  namespace: {{.Values.appName}}-build
spec:
  params:
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: 'https://github.com/mathianasj-backstage/{{.Values.name}}-quarkus/'
      name: url
      type: string
    - default: master
      name: revision
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/{{.Values.appName}}-build/{{.Values.name}}-quarkus:latest
      name: destImage
      type: string
    - default: 'no'
      name: nativeBuild
      type: string
    - default: 'false'
      name: skipPush
      type: string
  tasks:
    - name: checkout
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: build-service
      params:
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: SKIP_PUSH
          value: $(params.skipPush)
        - name: IMAGE
          value: $(params.destImage)
      runAfter:
        - checkout
      taskRef:
        kind: Task
        name: {{.Values.name}}-s2i-java
      when:
        - input: $(params.nativeBuild)
          operator: in
          values:
            - 'no'
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source
