kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.name }}-quarkus-gitops
  namespace: {{ .Values.appName }}-build
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
