kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eda-demo-dev
  namespace: {{ .Values.appName }}-build
subjects:
  - kind: ServiceAccount
    name: default
    namespace: eda-demo-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
