apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ .Values.name }}-update-deployment-tag
  namespace: {{ .Values.appName }}-build
spec:
  params:
    - name: appName
      type: string
    - name: PATH_CONTEXT
      type: string
    - name: gitopsurl
      type: string
    - name: imageTag
      type: string
  steps:
    - image: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8:v1.8'
      name: push-to-git
      resources: {}
      script: >
        #!/usr/bin/env sh

        set -eu

        ls $(workspaces.source.path)

        sed '-i' 's/            tag: [a-zA-Z0-9]*/            tag:$(params.imageTag)/g' $(workspaces.source.path)/components/$(params.appName)-argocd-app-dev.yaml

        git -C $(workspaces.source.path) config --local user.email "quarkus-ci+github-actions[bot]@users.noreply.github.com"
        git -C $(workspaces.source.path) config --local user.name "github-actions[bot]"
        git -C $(workspaces.source.path) commit -m "image update - release dev $(params.imageTag)" -a
        git -C $(workspaces.source.path) push $(params.gitopsurl) HEAD:master --follow-tags
      workingDir: $(workspaces.source.path)
      
  workspaces:
    - mountPath: /workspace/source
      name: source